### ISSUE TITLE
Item form

### ISSUE THREAD

**Issue by darinetag** [202306-NEA-DZ-FEW/team-f#13]
**Task title**
Item form

**Task description**
Create item form

**Subtasks**
The form contains the following:
- [ ] Add item title
- [ ] Title input
- [ ] Category input dropdown
- [ ] Date input dropdown
- [ ] Description input
- [ ] Upload image input
- [ ] Confirm and Cancel buttons

**Link to the component on Figma**
https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=118-540&mode=design&t=t3ddVdikt1RvahCU-4
