### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by darinetag** [202306-NEA-DZ-FEW/team-f#15]
**Task title**
Login Form

**Task description**
Create Login Form containing ( Email, password, login button )

**Subtasks**

- [ ] Log in title
- [ ] keep me logged in checkbox
- [ ] text if the user doesn't have an account ( sign up link )
- [ ] Forget password link
- [ ] Log in with ( socials: Facebook, Instagram, LinkedIn )

**Link to the component on Figma**
https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=210-2187&mode=design&t=t3ddVdikt1RvahCU-4
