### ISSUE TITLE
Authentication (login, sign up and logout) firebase 

### ISSUE THREAD

**Issue by Hadj-Said-Bouras** [202306-NEA-DZ-FEW/team-f#19]
**Task title**
Authentication (login, sign up, logout) firebase 

**Task description**
Create components for Login, sign up and log out buttons

**Subtasks**
- [ ] Create Login component
- [ ] Create Sign up component 
- [ ] Create Logout component
 
**Screenshots**
![image](https://github.com/ismail-benlaredj/recoded-capstone/assets/89461340/4c469d50-652f-41f2-bda3-a1293f472100)
![image](https://github.com/ismail-benlaredj/recoded-capstone/assets/89461340/0a55ecbb-7f1c-436f-a29d-d0e6174f05d5)

**Link to the component on Figma**
(https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=170-1320&mode=design&t=dgIF5X9Gs3w7QO5I-4)
https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=115-459&mode=design&t=bCAX85VlsfTlAttZ-4
