### ISSUE TITLE
Products management (Add, Delete and edit)

### ISSUE THREAD

**Issue by Hadj-Said-Bouras** [202306-NEA-DZ-FEW/team-f#21]
**Task title**
Products management (Add, Delete and edit)

**Task description**
Create a components for Add, Delete and edit items

**Subtasks**
- [ ] Create add component
- [ ] Create Delete component
- [ ] Create Edit component

**Screenshots**
![image](https://github.com/ismail-benlaredj/recoded-capstone/assets/89461340/e066aec9-ddf5-4017-8ee8-d0f47abc529c)
![image](https://github.com/ismail-benlaredj/recoded-capstone/assets/89461340/bce16ec5-8121-44fd-afc5-43add5ad143e)

**Link to the component on Figma**
https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=118-540&mode=design&t=dSaOXoAzOLScW1zg-4
https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=135-1957&mode=design&t=dSaOXoAzOLScW1zg-4
