### ISSUE TITLE
Blog : Article Card

### ISSUE THREAD

**Issue by SaraBegache** [202306-NEA-DZ-FEW/team-f#41]
**Task title**
Blog : Article Card

**Task description**
Create a Blog : Article Card

**Subtasks**

- [x] Create the ArticleCard component in the pages.
- [x] Pass the necessary props when using the component, providing data for each article card.
- [x] Repeat the usage of the ArticleCard component for each article to be displayed on the blog page.
- [x] Test the component's appearance and functionality to ensure it behaves as expected.
