### ISSUE TITLE
Main Layout

### ISSUE THREAD

**Issue by SaraBegache** [202306-NEA-DZ-FEW/team-f#44]
**Task title**
Main Layout

**Task description**
Create a layout for Main Page

**Subtasks**

- [x] Define the overall structure of the layout, including a header, navigation menu, content area, and footer.
- [x] Include elements like a logo, site title, and navigation links in the header.
- [x]  Add a navigation menu within the layout, often in the header.
- [x] Include links to different sections or pages of your application.l)

**Screenshots**
![layout](https://github.com/ismail-benlaredj/recoded-capstone/assets/30921501/ea5e426b-1e88-46b8-b1d3-0fcd31303caa)

**Link to the component on Figma**
Click the link [here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=93-44&mode=design&t=dFfYZG1e1w19jiMk-4)
