### ISSUE TITLE
Card Layout

### ISSUE THREAD

**Issue by SaraBegache** [202306-NEA-DZ-FEW/team-f#46]
**Task title**
Card Layout

**Task description**
Create Card Layout

**Subtasks**
- [ ] Determine what data you want to display on each card (e.g., title, description, image).
- [ ] Pass this data to the Card component as props.
- [ ] Set up dynamic routing to handle card clicks.

**Link to the component on Figma**
Click the link [here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=91-72&mode=design&t=dFfYZG1e1w19jiMk-4)
