### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by SaraBegache** [202306-NEA-DZ-FEW/team-f#47]
**Task title**
Article UI

**Task description**
Create an Article UI

**Subtasks**

- [ ] Implement data fetching to load the article content
- [ ] Set up dynamic routing for individual articles
- [ ] Implement SEO best practices by adding metadata such as title, description, and Open Graph tags to improve the article's discoverability and shareability
- [ ] Make the Article UI accessible by adding appropriate ARIA attributes and conducting accessibility testing

**Screenshots**
![article](https://github.com/202306-NEA-DZ-FEW/team-f/assets/30921501/536ae0c7-0cb5-48d5-a96f-18251ac2a8f8)

**Link to the component on Figma**
Click the link [here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?type=design&node-id=118-540&mode=design&t=CfnLq9kqU03J68rc-4)
